# Generated by Django 4.1.1 on 2022-11-01 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_certs_alter_jobs_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certs',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
