# Generated by Django 4.1.1 on 2022-11-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_certs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certs',
            name='cert_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certs',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
