# Generated by Django 4.1.1 on 2022-11-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_certs_cert_title_alter_certs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certs',
            name='cert_image',
            field=models.ImageField(blank=True, upload_to='static/storage/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='static/storage/images/'),
        ),
    ]
